### ISSUE TITLE
5.33.141.1 Download URL?

### ISSUE THREAD

**Issue by mevans-pai** [JousterL/SecWriteups#1]
Hi - do you have the download URL from the omadm.log for the 5.33.141.1 firmware? Mine won't seem to auto-update, but I can access the screen to upload a firmware manually. Thanks.

**Comment by JousterL** [comment]
Not directly from the logs, no, but if you follow the same URI as in the write-up, you can find it. 

`curl https://4g2.vzwdm.com/oma-dlserver/requestDD?imagename=WNC_LVSKIHP_1648140226730` returns a download URI of https://cdn2.vzwdm.com/WNC_LVSKIHP_Full_v5.33.117.1_To_v3.33.101.1.bin. 
The form of their CDN is always the same, so you should have luck modifying it in the form
https://cdn2.vzwdm.com/WNC_LVSKIHP_Full_v3.33.101.1_To_v5.33.141.1.bin.

That being said, you'll need to grab the one staged for your current version. Also it's possible there's a reason they are holding your firmware back in your area, so caveat lector.
